language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install .[testing]

# command to run tests
script:
  - pytest --cov=datasets --cov-report=xml

after_script:
  - codecov

notifications:
  email: false
